spring.application.name=rent-a-car

# MongoDB
spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/rentacar}

# JWT
jwt.secret=${JWT_SECRET:s3cr3tK3yF0rD3vEl0pm3ntT3st1ngPurp0s3sOnlyCh4ng3InPr0d}
jwt.expiration=${JWT_EXPIRATION:86400000}

# Server
server.port=${SERVER_PORT:8080}
