services:
  mongodb:
    image: mongo:7
    container_name: rentacar-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - rentacar-net

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: rentacar-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/rentacar
      JWT_SECRET: chave-secreta-jwt-producao-alterar-em-ambiente-real
      JWT_EXPIRATION: "86400000"
    depends_on:
      - mongodb
    networks:
      - rentacar-net

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: rentacar-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - rentacar-net

volumes:
  mongo-data:

networks:
  rentacar-net:
    driver: bridge
