export const PROFESSIONS: string[] = [
  'Administrador(a)',
  'Advogado(a)',
  'Agente de Viagens',
  'Agricultor(a)',
  'Analista de Sistemas',
  'Antropólogo(a)',
  'Arqueólogo(a)',
  'Arquiteto(a)',
  'Assessor(a) de Imprensa',
  'Assistente Social',
  'Astrônomo(a)',
  'Atleta Profissional',
  'Ator/Atriz',
  'Auditor(a)',
  'Biólogo(a)',
  'Biomédico(a)',
  'Bombeiro(a)',
  'Cabeleireiro(a)',
  'Chef de Cozinha',
  'Cientista da Computação',
  'Cientista de Dados',
  'Cientista Político(a)',
  'Cinegrafista',
  'Cirurgião/Cirurgiã',
  'Comissário(a) de Bordo',
  'Comunicador(a) Social',
  'Consultor(a)',
  'Contador(a)',
  'Corretor(a) de Imóveis',
  'Corretor(a) de Seguros',
  'Cozinheiro(a)',
  'Decorador(a)',
  'Dentista',
  'Designer',
  'Designer de Interiores',
  'Designer Gráfico',
  'Detetive',
  'Diplomata',
  'Diretor(a) de Cinema',
  'Economista',
  'Editor(a)',
  'Educador(a) Físico',
  'Eletricista',
  'Empreendedor(a)',
  'Empresário(a)',
  'Enfermeiro(a)',
  'Engenheiro(a) Ambiental',
  'Engenheiro(a) Civil',
  'Engenheiro(a) de Computação',
  'Engenheiro(a) de Produção',
  'Engenheiro(a) de Software',
  'Engenheiro(a) Elétrico',
  'Engenheiro(a) Mecânico',
  'Engenheiro(a) Químico',
  'Escritor(a)',
  'Estatístico(a)',
  'Esteticista',
  'Estilista',
  'Estudante',
  'Farmacêutico(a)',
  'Filósofo(a)',
  'Físico(a)',
  'Fisioterapeuta',
  'Fonoaudiólogo(a)',
  'Fotógrafo(a)',
  'Funcionário(a) Público(a)',
  'Garçom/Garçonete',
  'Geógrafo(a)',
  'Geólogo(a)',
  'Gerente',
  'Historiador(a)',
  'Influenciador(a) Digital',
  'Joalheiro(a)',
  'Jornalista',
  'Juiz/Juíza',
  'Laboratorista',
  'Leiloeiro(a)',
  'Linguista',
  'Logístico(a)',
  'Marceneiro(a)',
  'Matemático(a)',
  'Mecânico(a)',
  'Mediador(a)',
  'Médico(a)',
  'Mergulhador(a)',
  'Meteorologista',
  'Militar',
  'Minerador(a)',
  'Motorista',
  'Museólogo(a)',
  'Músico(a)',
  'Nutricionista',
  'Oceanógrafo(a)',
  'Oculista',
  'Odontólogo(a)',
  'Operador(a) de Máquinas',
  'Ótico(a)',
  'Paleontólogo(a)',
  'Paramédico(a)',
  'Pastor(a)',
  'Pedagogo(a)',
  'Pedreiro(a)',
  'Perito(a)',
  'Personal Trainer',
  'Pescador(a)',
  'Pesquisador(a)',
  'Piloto',
  'Pintor(a)',
  'Pizzaiolo(a)',
  'Policial',
  'Político(a)',
  'Produtor(a) Cultural',
  'Produtor(a) Rural',
  'Professor(a)',
  'Programador(a)',
  'Promotor(a) de Eventos',
  'Promotor(a) de Justiça',
  'Psicanalista',
  'Psicólogo(a)',
  'Psiquiatra',
  'Publicitário(a)',
  'Químico(a)',
  'Radialista',
  'Radiologista',
  'Recepcionista',
  'Redator(a)',
  'Relações Públicas',
  'Repórter',
  'Repositor(a)',
  'Representante Comercial',
  'Sapateiro(a)',
  'Secretário(a)',
  'Segurança',
  'Sociólogo(a)',
  'Sommelier',
  'Técnico(a) de Enfermagem',
  'Técnico(a) de Informática',
  'Técnico(a) de Laboratório',
  'Técnico(a) de Segurança do Trabalho',
  'Técnico(a) em Eletrônica',
  'Tecnólogo(a)',
  'Teólogo(a)',
  'Terapeuta Ocupacional',
  'Topógrafo(a)',
  'Tradutor(a)/Intérprete',
  'Turismólogo(a)',
  'Urbanista',
  'Vendedor(a)',
  'Veterinário(a)',
  'Vidraceiro(a)',
  'Vigilante',
  'Viticultor(a)',
  'Youtuber',
  'Zoólogo(a)',
];
